/**
 * Test factories — in-memory entity builders.
 *
 * Rules:
 * - All factories are pure (no DB I/O).
 * - Every factory accepts `overrides: Partial<T>` so callers can vary only what matters.
 * - IDs are deterministic so tests can assert on them without querying.
 * - Email, CPF, phone follow anonymisation rules from
 *   docs/10-architecture/10-testing-strategy.md §5.2.
 *
 * Spec: docs/10-architecture/10-testing-strategy.md §5
 */

import type { NewBrand } from '@/lib/db/schema/organization'
import type { NewUserAccount } from '@/lib/db/schema/organization'
import type { NewAuditLog } from '@/lib/db/schema/audit'
import type { NewTimelineEvent } from '@/lib/db/schema/timeline'
import type { NewWebhookLog } from '@/lib/db/schema/webhook-log'

// ---------------------------------------------------------------------------
// Fixed UUIDs for deterministic tests
// ---------------------------------------------------------------------------

export const FIXTURE_IDS = {
  brand: '10000000-0000-0000-0000-000000000001',
  user: '20000000-0000-0000-0000-000000000001',
  contact: '30000000-0000-0000-0000-000000000001',
  role: '40000000-0000-0000-0000-000000000001',
  permission: '50000000-0000-0000-0000-000000000001',
} as const

// ---------------------------------------------------------------------------
// Brand
// ---------------------------------------------------------------------------

/**
 * Returns a valid NewBrand shape.
 * INV-ORG-05: slug must be kebab-case (enforced by DB CHECK ck_brand_slug_kebab).
 */
export function makeBrand(overrides: Partial<NewBrand> = {}): NewBrand {
  return {
    name: 'CNE Carreiras',
    slug: 'cne-carreiras',
    logoUrl: null,
    primaryColor: null,
    ...overrides,
  }
}

// ---------------------------------------------------------------------------
// UserAccount
// ---------------------------------------------------------------------------

/**
 * Returns a valid NewUserAccount shape.
 * The `id` mirrors auth.users.id — it is not auto-generated by the DB.
 */
export function makeUser(overrides: Partial<NewUserAccount> = {}): NewUserAccount {
  return {
    id: FIXTURE_IDS.user,
    email: 'fixture-admin@example.com',
    fullName: 'Fulano de Tal',
    phone: '+5511999999999',
    isActive: true,
    totpEnabled: false,
    lastLoginAt: null,
    deletedAt: null,
    ...overrides,
  }
}

// ---------------------------------------------------------------------------
// ContactFixture
//
// The `contact` table does not exist in Sprint 0 (added in Sprint 1, T-1-xx).
// This type mirrors the minimal shape expected by emitTimelineEvent and by
// future tests that will use the real contact table.
// ---------------------------------------------------------------------------

export type ContactFixture = {
  id: string
  email: string
  fullName: string
  brandId: string
}

/**
 * Returns a contact-shaped fixture object (no DB required).
 */
export function makeContact(overrides: Partial<ContactFixture> = {}): ContactFixture {
  return {
    id: FIXTURE_IDS.contact,
    email: 'fixture-contato@example.com',
    fullName: 'Fulana Silva',
    brandId: FIXTURE_IDS.brand,
    ...overrides,
  }
}

// ---------------------------------------------------------------------------
// AuditLog
// ---------------------------------------------------------------------------

/**
 * Returns a valid NewAuditLog shape.
 * BR-AUDIT: ck_audit_actor — at least one of actorUserId or actorSystem must be non-null.
 */
export function makeAuditEntry(overrides: Partial<NewAuditLog> = {}): NewAuditLog {
  return {
    actorUserId: FIXTURE_IDS.user,
    actorSystem: null,
    actionKind: 'create',
    resourceKind: 'brand',
    resourceId: FIXTURE_IDS.brand,
    before: {},
    after: {},
    ip: null,
    userAgent: null,
    context: {},
    ...overrides,
  }
}

// ---------------------------------------------------------------------------
// TimelineEvent
// ---------------------------------------------------------------------------

/**
 * Returns a valid NewTimelineEvent shape.
 * INV-TIMELINE-02: at least one of actorUserId or actorSystem must be non-null.
 * INV-TIMELINE-03: kind must be snake_case.
 */
export function makeTimelineEvent(overrides: Partial<NewTimelineEvent> = {}): NewTimelineEvent {
  return {
    contactId: FIXTURE_IDS.contact,
    brandId: FIXTURE_IDS.brand,
    kind: 'contact_created',
    source: 'MOD-CONTACT',
    actorUserId: FIXTURE_IDS.user,
    actorSystem: null,
    subjectKind: null,
    subjectId: null,
    payload: { origin: 'manual' },
    occurredAt: new Date('2026-04-23T00:00:00Z'),
    ...overrides,
  }
}

// ---------------------------------------------------------------------------
// WebhookLog
// ---------------------------------------------------------------------------

/**
 * Returns a valid NewWebhookLog shape.
 * BR-INTEGRATION-IDEMPOTENCY: (provider, externalEventId) must be unique.
 */
export function makeWebhookLog(overrides: Partial<NewWebhookLog> = {}): NewWebhookLog {
  return {
    provider: 'digital_guru',
    externalEventId: 'guru_fixture_001',
    eventKind: 'transaction_approved',
    payload: { id: 'guru_fixture_001', status: 'approved' },
    ...overrides,
  }
}
